In [0]:
import pandas as pd

In [0]:
# Reading CSV file from URL
df=pd.read_csv('info.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [4]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
# To get description about columns like mean, min, max...
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [0]:
x=df.iloc[:,0:4].values

***IMPUTATION***

In [0]:
# Removing missing values or replacing missing value with some relevant data we use IMPUTER
from sklearn.preprocessing import Imputer

In [8]:
imp=Imputer(missing_values='NaN',axis=0,strategy='most_frequent')     # axis=0 - Check column wise. # strategy='mean/min/max' - replace the missing value with the mean.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
impute=imp.fit(x[:,1:3])    # This is only fitting of columns that we want to process

In [10]:
# Now time for transforming the fitted columns
x[:,1:3]=impute.transform(x[:,1:3])    # also replacing the missing values
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 48000.0, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 27.0, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

***LABEL ENCODING (LE)***

In [0]:
# Labelling the string type of data into INT/FLOAT , because classifier requires int/float values
from sklearn.preprocessing import LabelEncoder
cont=LabelEncoder()   # This is for labelling the country column

In [12]:
# Now Applying the column to the LabelEncoder ( Here Country column)
x[:,0]=cont.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 48000.0, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 27.0, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [13]:
purchase=LabelEncoder()
x[:,3]=purchase.fit_transform(x[:,3])
x

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 48000.0, 1],
       [0, 35.0, 58000.0, 1],
       [2, 27.0, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

***ONE HOT ENCODING (OHE)***

In [0]:
# --------Feature Scaling ---------
# Now enecoding first column  -- making subcolumns of first column..
# Why we do this :-  because while applying KNN like algorithm if we convert some value into number like country in 0,1,2... 
#      so in this case while calculating distance (x^2-x^1) if x=0 then machine will assume that x has no value, this will impact the model..

from sklearn.preprocessing import OneHotEncoder

In [0]:
# Defining exact column number where we want to make category
firstclm = OneHotEncoder(categorical_features=[0])  # 0 - The column where to apply

In [16]:
x=firstclm.fit_transform(x).toarray()    # After Transformation we need to convert into numpy array
x

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04, 1.0e+00],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04, 0.0e+00],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01, 4.8e+04, 1.0e+00],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04, 1.0e+00],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 5.2e+04, 0.0e+00],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04, 1.0e+00],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04, 0.0e+00],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04, 1.0e+00]])

In [17]:
x.astype(int)    # To display in integer only.

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 48000,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    27, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])